set tags+=../include/tags
set tags+=~/.vim/tags/ogre_lib			 " /usr/
set tags+=~/.vim/tags/ogre_main			 " ~/ogre/OgreMain/include/
set tags+=~/.vim/tags/ois                " /usr/include/OIS
set tags+=~/.vim/tags/ogre_sdk_sample	 " ~/ogre/Samples/
set tags+=~/.vim/tags/ogre_components	 " ~/ogre/Components/
set tags+=~/.vim/tags/ogre_renderSystems " ~/ogre/RenderSystems/
set tags+=~/.vim/tags/bullet			 " /usr/local/include/bullet/
set tags+=~/.vim/tags/bullet_main		 " ~/bullet/src/ >>> 4-19
set tags+=~/.vim/tags/ogre_bullet		 " /usr/local/include/OgreBullet/
set tags+=~/.vim/tags/OpenAL		 " OpenAL | /usr/local/include/AL/
set tags+=~/.vim/tags/OgreAL		 " OgreAL | /usr/local/include/OgreAL/
